version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: magneq-mongo
    restart: unless-stopped
    ports:
      - "27019:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: magneq
